# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_pref.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from mem import member
from pref import Preferences

class Ui_Dialog(object):

    def __init__(self):
        self.members = member()

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(637, 350)
        pref2 = Preferences()
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.tab_7)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 591, 251))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_20.setObjectName("label_20")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_21.setObjectName("label_21")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_22.setObjectName("label_22")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_23.setObjectName("label_23")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.lineEdit_11.setAccessibleName("")
        #
        self.lineEdit_11.setText(pref2.getapi_root_port())
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.lineEdit_12.setObjectName("lineEdit_12")
        #
        self.lineEdit_12.setText(pref2.getaccess_token())
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_12)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.lineEdit_13.setObjectName("lineEdit_13")
        #
        self.lineEdit_13.setText(pref2.getsecret())
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.lineEdit_14.setObjectName("lineEdit_14")
        #
        self.lineEdit_14.setText(pref2.getpost_url_port())
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_14)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_5)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 591, 251))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        #
        self.lineEdit.setText(pref2.getqqid())
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.textEdit = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        #
        self.textEdit.setText(pref2.getwelcome())
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.textEdit_2 = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.textEdit_2.setObjectName("textEdit_2")
        #
        self.textEdit_2.setText(pref2.getshutwords())
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textEdit_2)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 591, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.gridLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.comboBox.insertItems(0, ['SNH', 'BEJ', 'GNZ', 'SHY', 'CKG'])
        if pref2.getidolgroup():
            self.comboBox.setItemText(0, pref2.getidolgroup())
        #
        # if pref2.getidolgroup():
        #     self.comboBox.setItemText(0, pref2.getidolgroup())
        # else:
        #     self.comboBox.insertItems(0, ['SNH', 'BEJ', 'GNZ', 'SHY', 'CKG'])
        # self.comboBox.currentIndexChanged.connect(lambda : print('you change combox'))
        # end
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        #
        # end
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        #
        self.comboBox_3.addItems(list(map(lambda e: e[0], self.members.getroomidtuples(self.comboBox.currentText()))))
        if pref2.getidolname():
            self.comboBox_3.setItemText(0, pref2.getidolname())
        #end
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        #
        self.lineEdit_2.setText(pref2.getidolnick())
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        #
        self.lineEdit_3.setText(pref2.getroomid())
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_15.setObjectName("lineEdit_15")
        #
        self.lineEdit_15.setText(pref2.getroomid())
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_15)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 591, 251))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        #
        self.lineEdit_4.setText(pref2.getkduser())
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        #
        self.lineEdit_5.setText(pref2.getkdpassword())
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        #
        self.lineEdit_6.setText(pref2.gettoken())
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBox.setMinimum(10)
        self.spinBox.setMaximum(60)
        self.spinBox.setObjectName("spinBox")
        #
        try:
            self.spinBox.setValue(int(pref2.getkdinterval()))
        except:
            pass
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 591, 251))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_8.setObjectName("lineEdit_8")
        #
        self.lineEdit_8.setText(pref2.getproid())
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.spinBox_2 = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spinBox_2.setMinimum(10)
        self.spinBox_2.setMaximum(60)
        self.spinBox_2.setObjectName("spinBox_2")
        #
        try:
            self.spinBox_2.setValue(int(pref2.getmdinterval()))
        except:
            pass
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 591, 251))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_16.setObjectName("label_16")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_17.setObjectName("label_17")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_9.setObjectName("lineEdit_9")
        #
        self.lineEdit_9.setText(pref2.getweiboid())
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        #
        self.lineEdit_10.setText(pref2.getweibourl())
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_10)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_18.setObjectName("label_18")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.spinBox_3 = QtWidgets.QSpinBox(self.formLayoutWidget_4)
        self.spinBox_3.setMinimum(30)
        self.spinBox_3.setMaximum(300)
        self.spinBox_3.setObjectName("spinBox_3")
        #
        try:
            self.spinBox_3.setValue(int(pref2.getwbinterval()))
        except:
            pass
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_3)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.tab_6)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 591, 251))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_19.setObjectName("label_19")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.textEdit_3 = QtWidgets.QTextEdit(self.formLayoutWidget_5)
        self.textEdit_3.setObjectName("textEdit_3")
        #
        self.textEdit_3.setText(pref2.getproxy())
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEdit_3)
        self.tabWidget.addTab(self.tab_6, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        # self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.accepted.connect(lambda: self.clickaccept(Dialog))
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.comboBox.currentIndexChanged.connect(lambda: self.changegroup())
        self.comboBox_3.currentIndexChanged.connect(lambda: self.changemember())

    def changegroup(self):
        self.comboBox_3.clear()
        self.lineEdit_15.clear()
        # print(self.comboBox.currentText())
        str1 = list(map(lambda e: e[0], self.members.getroomidtuples(self.comboBox.currentText())))
        self.comboBox_3.addItems(str1)

    def changemember(self):
        self.lineEdit_3.clear()
        self.lineEdit_15.clear()
        try:
            roomid = self.members.getroomid(self.comboBox.currentText(), self.comboBox_3.currentText())
        except:
            pass
        else:
            self.lineEdit_3.setText(roomid)

    def clickaccept(self, Dialog):
        pref1 = Preferences()
        # coolq
        self.api_root_port = self.lineEdit_11.text()
        pref1.writeapi_root_port(self.api_root_port)
        self.access_token = self.lineEdit_12.text()
        pref1.writeaccess_token(self.access_token)
        self.secret = self.lineEdit_13.text()
        pref1.writesecret(self.secret)
        self.post_url_port = self.lineEdit_14.text()
        pref1.writepost_url_port(self.post_url_port)
        # qq group
        self.qunid = self.lineEdit.text()
        pref1.writeqqid(self.qunid)
        self.welcome = self.textEdit.toPlainText()
        pref1.writewelcome(self.welcome)
        self.shutword = self.textEdit_2.toPlainText()
        pref1.writeshutwords(self.shutword)
        # idol
        # if not self.lineEdit_2.text():
        #     self.idolname = self.comboBox_3.currentText()
        # else:
        #     self.idolname = self.lineEdit_2.text()
        # pref1.writeidolnick(self.idolname)
        self.idolname = self.comboBox_3.currentText()
        pref1.writeidolname(self.idolname)
        self.idolnick = self.lineEdit_2.text()
        pref1.writeidolnick(self.idolnick)
        if not self.lineEdit_15.text():
            self.roomid = self.lineEdit_3.text()
        else:
            self.roomid = self.lineEdit_15.text()
        pref1.writeroomid(self.roomid)
        # koudai48
        self.kduser = self.lineEdit_4.text()
        self.kdpsd = self.lineEdit_5.text()
        pref1.writekdaccount(self.kduser, self.kdpsd)
        self.kdinterval = self.spinBox.value()
        pref1.writekdinterval(self.kdinterval)
        # modian
        self.proid = self.lineEdit_8.text()
        pref1.writeproid(self.proid)
        self.mdinterval = self.spinBox_2.value()
        pref1.writemdinterval(self.mdinterval)
        # weibo
        self.wbid = self.lineEdit_9.text()
        pref1.writeweiboid(self.wbid)
        self.wbinterval = self.spinBox_3.value()
        pref1.writewbinterval(self.wbinterval)
        # proxy
        self.proxyhttps = self.textEdit_3.toPlainText()
        pref1.writeproxy(self.proxyhttps)
        Dialog.accept()



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_20.setText(_translate("Dialog", "api_root_port"))
        self.label_21.setText(_translate("Dialog", "access_token"))
        self.label_22.setText(_translate("Dialog", "secret"))
        self.label_23.setText(_translate("Dialog", "post_url_port"))
        self.lineEdit_11.setPlaceholderText(_translate("Dialog", "如 5700"))
        self.lineEdit_12.setPlaceholderText(_translate("Dialog", "可不填"))
        self.lineEdit_13.setPlaceholderText(_translate("Dialog", "可不填"))
        self.lineEdit_14.setPlaceholderText(_translate("Dialog", "如 8080"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "酷Q"))
        self.label.setText(_translate("Dialog", "QQ群号"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "可多个 用英文逗号隔开"))
        self.label_2.setText(_translate("Dialog", "欢迎信息"))
        self.textEdit.setPlaceholderText(_translate("Dialog", "可以直接用回车换行"))
        self.label_3.setText(_translate("Dialog", "禁言关键字"))
        self.textEdit_2.setPlaceholderText(_translate("Dialog", "可填多个 用英文逗号隔开"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "QQ"))
        self.label_4.setText(_translate("Dialog", "团属"))
        self.label_5.setText(_translate("Dialog", "队伍"))
        self.label_6.setText(_translate("Dialog", "姓名"))
        self.label_7.setText(_translate("Dialog", "自定义姓名"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "如：你的小可爱hzx"))
        self.label_8.setText(_translate("Dialog", "房间号"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "自动生成"))
        self.label_24.setText(_translate("Dialog", "自定义房间号"))
        self.lineEdit_15.setPlaceholderText(_translate("Dialog", "替代自动生成的房间号"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Idol"))
        self.label_9.setText(_translate("Dialog", "用户名"))
        self.label_10.setText(_translate("Dialog", "密码"))
        self.label_11.setText(_translate("Dialog", "Token"))
        self.lineEdit_6.setPlaceholderText(_translate("Dialog", "token会自动设置"))
        self.label_12.setText(_translate("Dialog", "msgTime"))
        self.label_13.setText(_translate("Dialog", "查询间隔(s)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "口袋"))
        self.label_14.setText(_translate("Dialog", "Pro_id"))
        self.label_15.setText(_translate("Dialog", "查询间隔(s)"))
        self.lineEdit_8.setPlaceholderText(_translate("Dialog", "可填多个 用英文逗号隔开"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "摩点"))
        self.label_16.setText(_translate("Dialog", "Container_id"))
        self.label_17.setText(_translate("Dialog", "url"))
        self.lineEdit_10.setPlaceholderText(_translate("Dialog", "自动生成"))
        self.label_18.setText(_translate("Dialog", "查询间隔(s)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "微博"))
        self.label_19.setText(_translate("Dialog", "HTTPS"))
        self.textEdit_3.setPlaceholderText(_translate("Dialog", "可不填 若填写多个则用英文逗号隔开 如：1.1.1.1:1234,2.2.2.2:1234"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "代理"))

